## NumPy Array Properties and Methods

NumPy arrays have several useful properties and methods that can be used to manipulate them.

- `shape`: Property that returns the dimensions of the array
- `ndim`: Property that returns number of array dimensions
- `dtype`: Property that returns data-type of the array’s elements
- `T`: Transpose of the array’s elements
- -------------------------------------------------------------------
- `reshape()`: Method to change the dimensions of an array. The product of old dimensions should match the product of new dimensions
- `ravel()`: Method that collapses all values into a single axis or dimension and returns view of original array
- `flatten()`: Method that collapses all values into a single axis or dimension and returns an independent copy of original array
- `sum()`: Method that returns the sum of all elements in an array
- `cumsum()`: Method that returns cumulative sum over given axis
- `prod()`: Method that compute product over given axis
- `max()`: Method that returns the maximum along a given axis
- `argmax()`: Method that returns indeces of the maximum values along a given axis
- `clip()`: Clip values beyond range to threshold values
- `np.concatenate()`: Method to concatenate two or more arrays
- `np.split()`: Method to split an array into multiple sub-arrays
- `np.vstack()`: Method to stack arrays vertically
- `np.hstack()`: Method to stack arrays horizontally

In [1]:
import numpy as np

In [2]:
a = np.random.randint(10, 50, size = (5,2,3))

In [3]:
a.shape

(5, 2, 3)

In [4]:
a.ndim

3

In [5]:
a.dtype

dtype('int64')

In [6]:
a.size # Number of elements

30

In [11]:
a.T # Matrix Transpose ( rows to columns , and columns to row)

array([[[29, 49, 35, 42, 19],
        [40, 18, 48, 27, 43]],

       [[18, 47, 11, 23, 17],
        [20, 30, 15, 20, 21]],

       [[37, 15, 21, 25, 38],
        [23, 47, 46, 19, 12]]])

---

In [16]:
a = np.random.randint(10, 50, size = (5,4))
a

array([[36, 26, 27, 25],
       [45, 16, 35, 36],
       [34, 24, 16, 48],
       [27, 30, 27, 48],
       [37, 31, 16, 17]])

In [21]:
a.reshape(10,2)

array([[36, 26],
       [27, 25],
       [45, 16],
       [35, 36],
       [34, 24],
       [16, 48],
       [27, 30],
       [27, 48],
       [37, 31],
       [16, 17]])

In [26]:
a.reshape(-1,5)

array([[36, 26, 27, 25, 45],
       [16, 35, 36, 34, 24],
       [16, 48, 27, 30, 27],
       [48, 37, 31, 16, 17]])

In [32]:
b = a.flatten() # a.ravel()
b

array([36, 26, 27, 25, 45, 16, 35, 36, 34, 24, 16, 48, 27, 30, 27, 48, 37,
       31, 16, 17])

In [34]:
a

array([[36, 26, 27, 25],
       [45, 16, 35, 36],
       [34, 24, 16, 48],
       [27, 30, 27, 48],
       [37, 31, 16, 17]])

In [35]:
a.sum(axis = 0)

array([179, 127, 121, 174])

In [36]:
a.sum(axis = 1)

array([114, 132, 122, 132, 101])

### 0 -> column wise -> vertival
### 1 -> row wise -> horizontal

In [39]:
np.trace(a)

np.int64(116)

In [40]:
np.cumsum(a, axis = 0)

array([[ 36,  26,  27,  25],
       [ 81,  42,  62,  61],
       [115,  66,  78, 109],
       [142,  96, 105, 157],
       [179, 127, 121, 174]])

In [48]:
np.prod(a, axis = 1)

array([ 631800,  907200,  626688, 1049760,  311984])

In [52]:
np.max(a, axis = 1)

array([36, 45, 48, 48, 37])

In [54]:
a

array([[36, 26, 27, 25],
       [45, 16, 35, 36],
       [34, 24, 16, 48],
       [27, 30, 27, 48],
       [37, 31, 16, 17]])

In [57]:
np.argmax(a, axis =0) 

array([1, 4, 1, 2])

In [60]:
np.clip(a, 20, 30)

array([[30, 26, 27, 25],
       [30, 20, 30, 30],
       [30, 24, 20, 30],
       [27, 30, 27, 30],
       [30, 30, 20, 20]])

In [76]:
arr1 = np.random.randint(1,100, size = (3,3))
arr2 = np.random.randint(1,100, size = (3,3))


In [77]:
arr1

array([[49, 15, 45],
       [91, 45, 61],
       [29, 59, 79]])

In [78]:
arr2

array([[47, 34, 60],
       [45, 81, 33],
       [89, 22, 11]])

In [81]:
d = np.concatenate([arr1,arr2], axis=0)
d

array([[49, 15, 45],
       [91, 45, 61],
       [29, 59, 79],
       [47, 34, 60],
       [45, 81, 33],
       [89, 22, 11]])

In [82]:
d = np.concatenate([arr1,arr2], axis=1)
d

array([[49, 15, 45, 47, 34, 60],
       [91, 45, 61, 45, 81, 33],
       [29, 59, 79, 89, 22, 11]])

In [85]:
np.vstack([arr1,arr2])

array([[49, 15, 45],
       [91, 45, 61],
       [29, 59, 79],
       [47, 34, 60],
       [45, 81, 33],
       [89, 22, 11]])

In [86]:
np.hstack((arr1,arr2))

array([[49, 15, 45, 47, 34, 60],
       [91, 45, 61, 45, 81, 33],
       [29, 59, 79, 89, 22, 11]])

In [93]:
np.split(d, 3, axis=1)

[array([[49, 15],
        [91, 45],
        [29, 59]]),
 array([[45, 47],
        [61, 45],
        [79, 89]]),
 array([[34, 60],
        [81, 33],
        [22, 11]])]