In [1]:
# !pip install numpy

In [2]:
import numpy as np

In [3]:
np.__version__

'2.4.0'

### Creating Numpy array

In [4]:
list1 = [2,3,4]

In [5]:
arr1 = np.array(list1)

In [6]:
arr1

array([2, 3, 4])

In [7]:
arr1.shape

(3,)

In [8]:
arr1.ndim

1

In [9]:
list1 = [[[2,3,4],[6,7,8], [6,8,0]],[[2,3,4],[6,7,8], [6,8,0]]]
arr1 = np.array(list1)

In [10]:
arr1

array([[[2, 3, 4],
        [6, 7, 8],
        [6, 8, 0]],

       [[2, 3, 4],
        [6, 7, 8],
        [6, 8, 0]]])

In [11]:
arr1.shape

(2, 3, 3)

In [12]:
arr1.ndim

3

NumPy arrays can be created in several ways. Here are some of the most common methods:

- `array()`: Creates NumPy arrays from Python lists
- `zeros()`: Creates NumPy arrays with all elements initialized to 0
- `ones()`: Creates NumPy arrays with all elements initialized to 1
- `full()`: Creates an array with all elements initialized to same user-specified value
- `arange()`: Creates NumPy arrays with a sequence of values (similar to python range() function)
- `linspace()`: Creates NumPy arrays with a sequence of evenly spaced values
- `diag()`: Creates NumPy array with the provided list of numbers as the diagonal elements and zeros elsewhere
- `eye()`: Creates NumPy array with ones on the diagonal and zeros elsewhere
- `identity()`: Creates an identity matrix
- `random.rand()`: Creates NumPy array of random numbers sampled from a uniform distribution

In [13]:
np.zeros((2, 3, 2), dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [14]:
np.full((3,4), fill_value=6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [15]:
np.arange(1,90,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86])

In [16]:
arr2 = np.linspace( (0,1,2) ,(10,20,30), num = 5)
arr2

array([[ 0.  ,  1.  ,  2.  ],
       [ 2.5 ,  5.75,  9.  ],
       [ 5.  , 10.5 , 16.  ],
       [ 7.5 , 15.25, 23.  ],
       [10.  , 20.  , 30.  ]])

In [17]:
arr2.shape

(5, 3)

In [18]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [19]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.randint(0,10,size = (2,3))

array([[6, 6, 1],
       [8, 4, 8]])

In [21]:
np.random.randint(0,50,size = (4,2,3))

array([[[13, 15,  4],
        [38,  2, 15]],

       [[ 4, 35, 38],
        [18,  2, 13]],

       [[35, 43, 40],
        [13,  8,  4]],

       [[26, 38, 22],
        [ 3, 30, 22]]])

## Accessing an Array

## Indexing and Slicing NumPy Arrays

NumPy arrays can be indexed and sliced in several ways depending on the number of dimensions.

### Indexing:

Indexing follows a simple rule that we may have encountered before. Let's give it a try.

- 1D Array: array_name[idx] (Similar to Python list)
- 2D Array: array_name[row_idx, col_idx] (Similar to Matrix)
- ND Array: array_name[dim1_idx, dim2_idx, ..., dimN_idx]

**OR**

- 2D Array: array_name[row_idx][col_idx]
- ND Array: array_name[dim1_idx][dim2_idx] ... [dimN_idx]


 ### Slicing:

Slicing follows the same rule as indexing. The only difference is that for each dimension we provide it with a range of indeces and sometimes (optional) step size (similar to arange() function discussed above).

- 1D Array: array_name[idx1:idx2:step]
- 2D Array: array_name[row_idx1:row_idx2:step1, col_idx1:col_idx2:step2]
- ND Array: array_name[dim1_idx1:dim1_idx2:step1, ..., dimN_idx1:dimN_idx2:stepN]

In [30]:
# 1D
a = np.array([1,2,4,5,6])

In [28]:
print(a[-3])

4


In [29]:
a[2::1]

array([4, 5, 6])

In [43]:
# 2D
arr = np.random.randint(0,10,size = (5,4))
arr

array([[9, 0, 7, 8],
       [6, 0, 5, 3],
       [1, 7, 2, 5],
       [9, 9, 9, 9],
       [1, 3, 8, 7]])

In [44]:
arr[1, 0] #or arr[1][0]

np.int64(6)

In [45]:
arr[-1, -1]

np.int64(7)

In [47]:
# Slicing 2D array : (array[<row_slice>, <col_slice>])
arr[1:3, 0:3]

array([[6, 0, 5],
       [1, 7, 2]])

In [48]:
arr[:2,3]

array([8, 3])

In [49]:
# 3D
arr = np.random.randint(0,10,size = (3,4,3))
arr

array([[[6, 7, 6],
        [6, 2, 0],
        [0, 9, 9],
        [0, 4, 2]],

       [[0, 3, 5],
        [1, 8, 4],
        [8, 9, 6],
        [6, 2, 4]],

       [[0, 7, 5],
        [9, 0, 7],
        [7, 7, 0],
        [8, 9, 3]]])

In [50]:
arr[1, -1, 2]

np.int64(4)

In [51]:
arr[1]

array([[0, 3, 5],
       [1, 8, 4],
       [8, 9, 6],
       [6, 2, 4]])

In [53]:
arr[:, :2, :]

array([[[6, 7, 6],
        [6, 2, 0]],

       [[0, 3, 5],
        [1, 8, 4]],

       [[0, 7, 5],
        [9, 0, 7]]])

In [54]:
dataset = np.random.randint(0,255, (16,3,720,720))

In [56]:
dataset.shape

(16, 3, 720, 720)

In [67]:
dataset[0,1, :,:]

array([[112,  75,  45, ...,  50, 110, 213],
       [252, 195, 107, ..., 225, 214, 183],
       [174,  15,  72, ...,  83, 194, 225],
       ...,
       [ 55, 211,  73, ..., 228,  43,  65],
       [ 11, 245, 127, ...,  67,   0, 102],
       [170, 207, 204, ..., 125,  63, 154]], shape=(720, 720))